### ISSUE TITLE
Trying to Sync with Sheet that API Key cannot access needs to be more obvious that it cannot access

### ISSUE THREAD

**Issue by TaylorBarrick** [lex-obrien/goSmartSheet#4]
When trying to access a sheet that was not shared with the API Key holder, the sheet comes back with default values, and no indication that it is not accessible.

**Comment by lex-obrien** [comment]
Fixed in the most recent push to master.  The value will be returned as a nil Sheet and the error will contain an appropriate error message.

I still want to change it up so that it returning a more proper error and also get rid if the *Sheet in favor of having people use the error messages.  But, that is for next time :)  

At least, it will not error silently!

**Comment by lex-obrien** [comment]
fixed in https://github.com/lex-obrien/goSmartSheet/commit/c9f4c504afb6f42ab78c052947ffdef2ef3ebdfa
